---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_major_version}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - remove
    - openssh

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package remove openssh'
  package:
    state: 'absent'
    name: "{{package_name_openssh}}"
    install_recommends: 'no'
  tags:
    - remove
    - openssh

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file remove banner'
  file:
    state: 'absent'
    path: "{{file_dst_banner}}"
  tags:
    - remove
    - openssh

- name: 'file remove moduli'
  file:
    state: 'absent'
    path: "{{file_dst_moduli}}"
  tags:
    - remove
    - openssh

- name: 'file remove ssh_config'
  file:
    state: 'absent'
    path: "{{file_dst_ssh_config}}"
  tags:
    - remove
    - openssh

- name: 'file remove sshd_config'
  file:
    state: 'absent'
    path: "{{file_dst_sshd_config}}"
  tags:
    - remove
    - openssh
